name: VersionScanLinkBuild

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker pull minddocdev/node-alpine:latest
        docker tag minddocdev/node-alpine:latest lalitku/hybrid-launch-artifact:Comp1-1.2.3-${{ github.run_number }}-4.5.6 --label build.url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} .
        docker images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: lalitku
        password: Lalit/2698
    - name: Push
      run: |
          docker push lalitku/hybrid-launch-artifact:Comp1-1.2.3-${{ github.run_number }}-4.5.6
    - name: Import Component Into UCD
      run: |
        curl --insecure --request PUT 'https://10.134.119.250:8443/cli/component/integrate' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data '{"component": "PdmComponent","properties": {"version": Comp1-1.2.3-${{ github.run_number }}-4.5.6,"description": ""}}'
    - name: Wait for 1m
      run: sleep 60
    - name: Create Snapshot
      run: |
        curl --insecure --request PUT 'https://10.134.119.250:8443/cli/snapshot/createSnapshot' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data '{"name": July-2023-RC-${{ github.run_number }},"application": "PdmApp","description": "Some snapshot","versions": [{"PdmComponent": "latest"}]}'
